### ISSUE TITLE
"QuickDrag" plugin conflict

### ISSUE THREAD

**Issue by toor2** [CAFxX/ImageTweak#1]
If you have "QuickDrag" plugin installed, dragEnd event cause save image action. Can you prevent this behaviour when left mouse used for image movement?

**Comment by CAFxX** [comment]
I'd rather not disrupt the workings of another extension. But the other extension (QuickDrag) could voluntarily "back off" by checking if ImageTweak is enabled (the preferred method to check for the presence of ImageTweak can be found in the README.md file).

**Comment by CAFxX** [comment]
I tried to get in touch with the author of QuickDrag but I didn't get any reply. If you can, please point him to this discussion.
