### ISSUE TITLE
Broken fullscreen modus

### ISSUE THREAD

**Issue by Speravir** [CAFxX/ImageTweak#11]
With version 0.22 and Firefox 5.0 I can't go into fullscreen (menu or F11 key). I could reproduce this in a new profile, where I deactivated all those automatically installed Java and Microsoft extensions.

The „User agent“ is: Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0 – i.o.w. my OS is WinXP (SP3).

**Comment by CAFxX** [comment]
When does this happen? When viewing a normal webpage or when displaying an image? Does it happen even if you don't switch between tabs? What's the value of the "extensions.imagetweak.automaticfullscreen" preference in about:config?

**Comment by Speravir** [comment]
It happens in both cases. I didn't change any of the preferences, so the value of „extensions.imagetweak.automaticfullscreen“ was „false“, but with „true“ it gets really weird: Then it works once with images, not with normal pages. Trying to going back from fullscreen into window mode results in strange behavior, that I do not understand. In my normal profile there are some more problems with other extensions.

What do you mean with not switching the tabs?

BTW: I installed imagetweak 0.21 into FFx 5 (i've patched the install.rdf) and this works fine!

**Comment by Speravir** [comment]
I've noticed there's a new preference „extensions.imagetweak.loggingenabled“. But if activated where can I see the log file?

**Comment by Speravir** [comment]
I've forgotten the error console:
After start of Firefox there comes first a message (Could not read chrome manifest file 'C:\Programme\Netzwerk\Firefox\extensions{972ce4c6-7e08-4474-a285-3208198ce6fd}\chrome.manifest'.),
then one warning, which is in German, see below, my translation attempt: warning – XUL-box for _moz_generated_content_after-element contains an inline-#text-child-element, that forces all children to be surrounded by a block – line 0,
third one error message: view.selection is null – source file: chrome://global/content/config.js – line: 368. This line is:
„var prefCol = view.selection.currentIndex < 0 ? null : gPrefView[view.selection.currentIndex].prefCol;“
After that there are two more informational messages: first says „fit false“, second says „pixel“.

When I try to go into fullscreen mode, there comes no new message/warning/error.

If there is a debug build or sysinternal tool or similar, let me know.

German warning:
Warnung: XUL-Box für _moz_generated_content_after-Element enthält ein Inline-#text-Kind-Element, was alle Nachkommen zwingt, von einem Block umgeben zu werden.
Quelldatei: chrome://browser/content/browser.xul
Zeile: 0= )

**Comment by kurttu** [comment]
I've been having the same problem with Firefox versions 5.0.1 and now 6.0, ImageTweak 0.22. When ever ImageTweak extension is enabled, pressing F11 will make Firefox briefly flash the screen in full mode and revert back to normal mode. My workaround is setting "extensions.imagetweak.automaticfullscreen" true and using the back button to exit full screen.

**Comment by CAFxX** [comment]
Yep sorry about that. I've removed the fullscreen stuff from 0.23. You can try the beta (https://github.com/downloads/CAFxX/ImageTweak/ImageTweak.0.23.b1.xpi) and report if you see any bugs.

**Comment by Speravir** [comment]
Works fine here. Thanks a lot!
(I've only tested the fullscreen behaviour.)

I think we can close this bug.
