### ISSUE TITLE
Color Management Prefs (Image Tweak 0.23 dev)

### ISSUE THREAD

**Issue by Cyberbeing** [CAFxX/ImageTweak#12]
There are currently a couple issues with the Color Management preferences.

The first issue has to do with the gfx.color_management.display_profile .
No profile specified means Firefox will automatically use the default system profile assigned to your monitor.
Image Tweak has no ICC profile specified listed as 'Disabled', which is incorrect. 'Disabled' should be changed to 'Use System Profile'.

The next issue is related to the above concerning gfx.color_management.mode .
When you select the current 'Disabled' entry (the one which should be 'Use System Profile'), the checkbox for 'Assume sRGB for untagged elements' is grayed out.
The 'Assume sRGB for untagged elements' checkbox should be available when not explicitly specifying an ICC profile, since Color Management is still enabled.

The last issue is if you truly do want to offer the capability to disable Color Management in Firefox (which is enabled by default) and/or allow tweaking of the renderering intent through ImageTweak.

Color Management Disabled is equivalent to gfx.color_management.mode = 0

Rendering intent specified by the image is equivalent to gfx.color_management.rendering_intent = -1

Perceptual intent is equivalent to gfx.color_management.rendering_intent = 0 (Firefox default)

Relative colorimetric intent is equivalent to gfx.color_management.rendering_intent = 1

Saturation intent is equivalent to gfx.color_management.rendering_intent = 2

Absolute colorimetric intent is equivalent to gfx.color_management.rendering_intent = 3

**Comment by CAFxX** [comment]
Thanks for the report, but this is a known issue (that's one of the reasons I haven't published 0.23 yet).
Unfortunately, when you leave the display_profile to the default value there appears to be no way to detect if Firefox was able to detect and use the "default" display profile and, in that case, to get which profile is currently in use (any suggestion is more than welcome!)
Unless I can figure this out, color management in IT will probably go the way of the dodo.

**Comment by Cyberbeing** [comment]
You would probably need to file a feature request for that on Bugzilla. The currently active (auto-detected) ICC profile does seem like something that belongs on about:support.

Firefox auto-detects the active profile by reading the Registry, but I doubt extensions are able to do that for security reasons.

That said, was there a particular reason Image Tweak would even need to know the currently active profile? If you just want to expose Firefox about:config functionality with a GUI, I don't see why knowing the active profile is needed. Normally you would never want to be manually selecting a profile unless you are troubleshooting, considering your profile will change every time you calibrate. Color Management is always active unless explicitly disabled, even if Firefox doesn't find a profile, it just falls back to a built-in sRGB profile afaik.

Off-topic, but if you are interested in Firefox Color Management in general, it looks like ICCv4 and XYZ/LAB LUT support may make it in Firefox 8 if testing goes well.

**Comment by CAFxX** [comment]
> Firefox auto-detects the active profile by reading the Registry, but I doubt extensions are able to do that for security reasons.

extensions can read the registry; the problem is that it's not really portable (linux? mac os? android?)

> That said, was there a particular reason Image Tweak would even need to know the currently active profile?

What if the OS chose the wrong profile? (e.g. sRGB when there's a proper monitor profile available)
Also, I'm not really confortable placing a menu item that might mean, depending on how the OS is configured, either color-management disabled (sRGB), color management active but wrong (wrong profile), color management active and correct (correct profile). I'd like to be able to at least tell the user which color profile is the default.

**Comment by Cyberbeing** [comment]
Yep, the lack of portability means you would need to have OS specific code paths.

What if the OS chose the wrong profile? The OS can't choose the wrong profile. If the profile is wrong, it would be user-error not OS-error. Should an extension be worrying about user-error which can't be corrected within Firefox? Though if you are uncomfortable implementing it, that is probably for the best. Chances are most users wouldn't know what to do with any of the color management options and end up misconfiguring them...

I did ping one of the qcms guys, and while he said he's interested in having more qcms information (like active profile) exposed to the user, nobody has taken initiative to start coding or even planning anything yet.

**Comment by CAFxX** [comment]
Actually this functionality is already available, unfortunately it's not scriptable so I can't access it from javascript:
http://mxr.mozilla.org/mozilla-central/source/gfx/thebes/gfxPlatform.h#399
