### ISSUE TITLE
Ctrl++ and Ctrl+- do not work on the Welcome page, page does not scale with text.

### ISSUE THREAD

**Issue by aleksejrs** [CAFxX/ImageTweak#16]
ImageTweak
Firefox 7.0b2 or 6.0 on Debian GNU/Linux x86_64.

chrome://imagetweak/content/welcome.htm

If the text size set in Preferences (Options) is bigger than 17 (small for me), the page becomes a mess because of overlapping text.

Full page zoom does not change "overlapped" status of the text (so it is equally overlapped, big size or small size).
With text-only zoom, it is as overlapped as it would be if that font size was selected in Preferences.

So if you don't like to read text of size under 18, the only way to read the text on the Welcome page is to go to Preferences.

**Comment by CAFxX** [comment]
Fixed by specifying the font-size. Unfortunately it's the only fix currently possible because the design of the page doesn't allow the font size to be changed while preserving the correct layout.
