### ISSUE TITLE
Completely doesn't work.

### ISSUE THREAD

**Issue by knoajp** [CAFxX/ImageTweak#18]
(Maybe since I update Firefox 5 to 6, or 4 to 5, or Windows XP to 7...)
ImageTweak is enabled, but doesn't work. None of the features appear.
It also happen with clean profile.

ImageTweak 0.23 and 0.23b1.
Firefox 6.0.1 and 6.0.2.
Windows 7 64bit SP1

**Comment by CAFxX** [comment]
Are there any messages in the Firefox error console that can be traced back to ImageTweak?

**Comment by knoajp** [comment]
Thanks.
"Firefox error console" means that firebug's console pane on image url ?
I tried firebug's console, Firefox's error console and Firefox's web console.
There are no error messages.

Is it happen for only me ? :-(

**Comment by CAFxX** [comment]
Yes, I meant the Firefox's error console (ctrl+shift+j on my locale)
It's the first time I hear about this, so I really have no idea what might be causing this. Which locale are you on? 
Does this happen also on a clean profile with no other extensions installed and no tabs from the previous session? In this case, are there no error messages on the Firefox error console?

**Comment by knoajp** [comment]
My locale is ja-JP.

I make new clean profile just for this test.
Error console is up with ctrl+shift+j and is blank.
There are just 2 tabs, addon(there's only ImageTweak) and large jpeg image below.
http://ricoh.co.jp/dc/gr/digital4/img/sample_01.jpg

No error message in console even if I reload image with Ctrl+F5.
Oh, I tried ImageTweak option in addon tab now, and see errors below!!
(Just copy and paste, no translation, but might be helpful ?)

**

警告: 'background-color' の値をパース中にエラーが発生しました。  このスタイル宣言は無視されました。
ソースファイル: chrome://imagetweak/content/prefs.xul
行: 0

警告: getElementById() に空文字列が渡されました。
ソースファイル: chrome://imagetweak/content/prefs.xul
行: 0

エラー: gBrowser is not defined
ソースファイル: chrome://imagetweak/content/imagetweak.js
行: 943

警告: WARN addons.manager: Exception calling callback: [Exception... "'[JavaScript Error: "gBrowser is not defined" {file: "chrome://imagetweak/content/imagetweak.js" line: 943}]' when calling method: [extIExtensionsCallback::callback]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: resource:///components/fuelApplication.js :: <TOP_LEVEL> :: line 1354"  data: yes]
ソースファイル: resource:///components/fuelApplication.js
行: 1354

**Comment by CAFxX** [comment]
This is very strange; gBrowser should always be available (once the browser has fully started). 
Do other extensions work fine?

**Comment by knoajp** [comment]
Yes.
Every addons work fine in my profile, and no other problems in test profile (only ImageTweak is installed).
Error messages are exactly same for each profiles.
I tried to confirm wheather I get errors of some other addons' option view in my profile, and get no errors.

**Comment by knoajp** [comment]
I finally detect the problem. Japanese language file "{DB2EA31C-58F5-48b7-8D60-CB0739257904}.xpi\locale\ja-JP\imagetweak.ent" is broken. It has no contextmenu entities. I don't know the reason...

Here is my complement+ (contains some fixes of older version).
// can i submit such a xml entities...? "percent" for & # 3 7 ; is okay?
**
<!ENTITY pref.window.title "ImageTweak - オプション">
<!ENTITY pref.prefpane.label "画像表示オプション">
<!ENTITY pref.bgcolor.label "背景色">
<!ENTITY pref.bordercolor.label "外枠色">
<!ENTITY pref.autoresize.label "読み込み時に画像を自動リサイズする">
<!ENTITY pref.clip_movement.label "画像の移動範囲を制限する">
<!ENTITY pref.zoomexp.label "拡大係数 (&#37;)">
<!ENTITY pref.zoomonpointer.label "マウスポインタに拡大する">
<!ENTITY pref.zoomtype.label "有効にする拡大形式">
<!ENTITY pref.zoomtype.default.label "既定の拡大形式">
<!ENTITY pref.zoomtype.full.label "ウィンドウ内に収める">
<!ENTITY pref.zoomtype.fill.label "ウィンドウをいっぱいにする">
<!ENTITY pref.zoomtype.free.label "自由様式">
<!ENTITY pref.zoomtype.unscaled.label "1:1">
<!ENTITY pref.shortcut.label "ショートカット有効 (Ctrl+右クリック)">
<!ENTITY pref.shortcut.img.label "画像 (IMG)">
<!ENTITY pref.shortcut.bg.label "背景">
<!ENTITY pref.invertmousewheel.label "マウスホイールの拡大方向を反転する">
<!ENTITY pref.invertkeyboard.label "キーボードナビゲーションを反転する">
<!ENTITY pref.startfromtopleft.label "画像を左上に配置する">
<!ENTITY pref.contentdetectable.label "Notify websites">
<!ENTITY pref.bgcolor.tooltip "画像を表示する時に利用する背景色を設定します">
<!ENTITY pref.bordercolor.tooltip "画像の外周に表示する枠の色を設定します。空欄なら外枠は表示しません。">
<!ENTITY pref.autoresize.tooltip "読み込みの際にウィンドウよりも大きな画像がウィンドウに収まるよう自動リサイズします">
<!ENTITY pref.clip_movement.tooltip "画像をウィンドウ内部でのみ動かすようにします">
<!ENTITY pref.zoomexp.tooltip "拡大段階係数 (200&#37; なら段階ごとに2倍・半分にすることを意味します)">
<!ENTITY pref.zoomonpointer.tooltip "スクロールホイール利用時にマウスポインタに向かって拡大します">
<!ENTITY pref.zoomtype.full.tooltip "ダブルクリック時にウィンドウ内に収める表示を有効にします">
<!ENTITY pref.zoomtype.fill.tooltip "ダブルクリック時にウィンドウいっぱいの表示を有効にします">
<!ENTITY pref.zoomtype.free.tooltip "ダブルクリック時に拡大とドラッグが可能な自由表示を有効にします">
<!ENTITY pref.zoomtype.unscaled.tooltip "ダブルクリック時の元倍率表示を有効にします">
<!ENTITY pref.shortcut.img.tooltip "ウェブページの中で利用されている画像から直接ImageTweakを起動するショートカットを有効にします">
<!ENTITY pref.shortcut.bg.tooltip "ウェブページの中で利用されている背景から直接ImageTweakを起動するショートカットを有効にします">
<!ENTITY pref.invertmousewheel.tooltip "拡大に関するマウスホイールのスクロール方向を反転します">
<!ENTITY pref.invertkeyboard.tooltip "スクロールに関する矢印キーの方向を反転します">
<!ENTITY pref.startfromtopleft.tooltip "ウィンドウより大きな画像を左上に配置します">
<!ENTITY pref.contentdetectable.tooltip "画像ビューアが使えるブラウザであることを、ウェブサイトに知らせます">
<!ENTITY pref.pressf1forhelp.label "F1 を押してオンラインヘルプを表示">
<!ENTITY about.window.title "ImageTweak について">
<!ENTITY pref.mousewheel.label "マウスホイール">
<!ENTITY pref.mousewheel.new.label "ホイールでスクロール、Ctrl+ホイールでズーム">
<!ENTITY pref.mousewheel.new.tooltip "Firefoxの規定のホイール動作です">
<!ENTITY pref.mousewheel.legacy.label "Ctrl+ホイールでスクロール、ホイールでズーム">
<!ENTITY pref.mousewheel.legacy.tooltip "ImageTweak 0.17から使われているホイール動作です">
<!ENTITY pref.contextmenu.label "コンテキストメニューを有効化">
<!ENTITY pref.contextmenu.tooltip "画像を操作するためのコンテキストメニューを有効にします">
<!ENTITY pref.resamplingalgorithm.label "画像処理アルゴリズム">
<!ENTITY pref.resamplingalgorithm.nearestneighbor.label "最近傍補間">
<!ENTITY pref.resamplingalgorithm.nearestneighbor.tooltip "速いけど品質は落ちます">
<!ENTITY pref.resamplingalgorithm.bilinear.label "線形補間">
<!ENTITY pref.resamplingalgorithm.bilinear.tooltip "最近傍補間よりやや遅いけど高品質です">
<!ENTITY contextmenu.fit.label "画像をウィンドウ内に収める">
<!ENTITY contextmenu.fill.label "画像をウィンドウいっぱいにする">
<!ENTITY contextmenu.unscaled.label "100&#37;">
<!ENTITY contextmenu.zoomin.label "拡大">
<!ENTITY contextmenu.zoomout.label "縮小">
<!ENTITY contextmenu.rotateclock.label "右回転">
<!ENTITY contextmenu.rotatecounter.label "左回転">
<!ENTITY contextmenu.options.label "ImageTweak オプション...">
<!ENTITY contextmenu.userguide.label "ImageTweak ユーザーガイド">

**Comment by knoajp** [comment]
Okay, not okay.
If you use above, replace "%" for "& # 3 7 ;"(delete spaces).

**Comment by knoajp** [comment]
and I find mistype in "\content\prefs.xul" of line 95-96.

original:
                        <radio label="&pref.resamplingalgorithm.nearestneighbor.label;" tooltip="&pref.resamplingalgorithm.nearestneighbor.tooltip;" value="0"/>
                        <radio label="&pref.resamplingalgorithm.bilinear.label;" tooltip="&pref.resamplingalgorithm.bilinear.tooltip;" value="1"/>

fix: (tooltip>tooltiptext)
                        <radio label="&pref.resamplingalgorithm.nearestneighbor.label;" tooltiptext="&pref.resamplingalgorithm.nearestneighbor.tooltip;" value="0"/>
                        <radio label="&pref.resamplingalgorithm.bilinear.label;" tooltiptext="&pref.resamplingalgorithm.bilinear.tooltip;" value="1"/>

**Comment by knoajp** [comment]
wow, ... but you may find it !! :-)

**Comment by MaximeC** [comment]
Hi,

Same thing here.

I'm running Firefox 8.0 on Ubuntu 11.10.
My locale is fr_FR.UTF-8.
I use the English language pack for Firefox (Ubuntu package). I tried before with the French language pack, same thing.
I use a fresh new Firefox profile with ImageTweak 0.23 addon, all other addons disabled.

When I start Firefox with a new session (did not even tried to look at a picture), I can find this in the error console :
---8<----------------------
Error: undefined entity
Source File: chrome://imagetweak/content/overlay.xul
Line: 45, Column: 3
Source Code:
  <menuitem class="menuitem-iconic" image="chrome://imagetweak/skin/search.png" id="context-imagetweak-fit" insertbefore="context-copyimage-contents" label="&contextmenu.fit.label;" oncommand="gContextMenu.target.ownerDocument.ImageTweak.PerformZoomTypeSwitch('fit', true);"/>
---8<----------------------

I hope it will help you to solve this issue, I was used to use this add-on.

**Comment by CAFxX** [comment]
Should be fixed on trunk:
https://github.com/CAFxX/ImageTweak/commit/d84e89f232e9a7d0dfe3f322a27135f623156194
https://github.com/CAFxX/ImageTweak/commit/c7b3e085f593a848263807af180f7995a47726b8
Please report any further issues.

**Comment by CAFxX** [comment]
also: https://github.com/CAFxX/ImageTweak/commit/ea8709d9dd9317d695f9342fe05c1bded78f818a
