### ISSUE TITLE
Firefox 4, dragging pictures

### ISSUE THREAD

**Issue by ghost** [CAFxX/ImageTweak#2]
At all Firefox 4 Betas and also at the new RC1 I have the bug that when I drag a zoomed in picture over the screen I see a transparent smaller version of this picture at my mouse pointer. Very similar to when you drag any picture on a website. Also it seems that picture dragging was much smoother at Firefox 3.

Thank you so much for ImageTweak. I use it on a daily basis and I worry what I will do if this project won't be supported anymore.

**Comment by CAFxX** [comment]
Hopefully I fixed the drag image issue: https://github.com/CAFxX/ImageTweak/commit/2cf093d06922033bece0a7b6829bfb3a952fd1b0

Please open a different issue for the dragging smoothness problem.

**Comment by CAFxX** [comment]
I'm closing the dragging image issue because it's fixed. Please open a new one for the smoothness problem.

**Comment by CAFxX** [comment]
Followup: https://github.com/CAFxX/ImageTweak/issues#issue/3
