### ISSUE TITLE
Images improperly centering in Aurora 11

### ISSUE THREAD

**Issue by Bieeanda** [CAFxX/ImageTweak#22]
Windows 7 64-bit, Firefox Aurora 11.0a2, ImageTweak 0.23; attempted with a brand-new profile with no other addons installed.

When viewing an image that is substantially smaller than the browser window in one or both dimensions, the addon seems to be determining the center of the window and lining the top and/or left edge with that point, instead of adjusting for the dimensions of the image. The effect is unfortunately rather lopsided, but not a critical issue.

**Comment by CAFxX** [comment]
Known issue due to a change to Firefox that upstreamed a few ImageTweak ideas. Will be fixed soon (hopefully).
https://bugzilla.mozilla.org/show_bug.cgi?id=376997

**Comment by Devices** [comment]
I am using Firefox Nightly 12.0a1, ImageTweak 0.23 and I have the same problem.

I know I am using a beta version so I don't expect a fix, just letting you know it exists and confirming the issue of the OP.

**Comment by CAFxX** [comment]
Sure, the patch went in just before the branching of fx11 so this bug is expected to be present in all versions from fx11 onward.

**Comment by Bieeanda** [comment]
Thanks for the quick response! And what Devices said-- I know I can't expect things to work perfectly when they're built onto test code, but wanted to mention it just in case.

**Comment by CAFxX** [comment]
Fixed on trunk
