### ISSUE TITLE
When I can zoom in, I cant click on the picture to zoom in

### ISSUE THREAD

**Issue by libraryaddict** [CAFxX/ImageTweak#24]
I dont like double clicking the picture and I often come across large pictures.

I dont know if this was removed because it was thought a feature.

Basically this : http://thumbs.dreamstime.com/thumblarge_279/1213450597M6358P.jpg

Has disappeared and I would love it back.
Even if you needed a option to turn it on.

If this is meant to be in Requests, I couldnt see a way to put it in there.

**Comment by CAFxX** [comment]
Ok, but clicking is also used for dragging. What happens if you click and then start dragging? Zoom-in-and-drag? Zoom-in-zoom-out-and-drag? Just-drag?

**Comment by CAFxX** [comment]
libraryaddict, I see no way to fix this without impacting the UX a lot. Feel free to reopen this if you can come up with a more complete proposal (see my questions above) that won't impact all other users.
