### ISSUE TITLE
Zoom scale is missed up when tabs bar dis/appear in full screen

### ISSUE THREAD

**Issue by ENigma885** [CAFxX/ImageTweak#26]
**Problem:
- In full screen FF with tab bar set to autohide, if a large image is zoomed to "Fill screen" or "Fit image to screen", hovering to show the tab bar resets the zoom to 100%.

---

**How to reproduce:
NOTE: Autohide tab bar in full screen is a default behavior in FF.
1- Open a large image, larger than your display screen's width or length.
You can use http://interfacelift.com/wallpaper/Da052882/02984_durdledoor_1600x1200.jpg
or http://interfacelift.com/wallpaper/details/2984/durdle_door.html and select a larger resolution than your current display.
(the site has some ads you'd better enable ABP while browsing)
2- Enter full screen (by pressing F11)
The  tab bar should be hidden now.
3- Set the open image to  to "Fill screen" or "Fit image to screen" from the right click menu or by multiple left clicks.
4- Hover to the top to show the tabs bar.
RESULT: Image zoom is reset back to 100%

---

**Environment:
- Image Tweak 0.25
- Firefox 13.0.1
- Ubuntu 12.04 and also tried on Windows 7 with the same IT and FF versions

---

**Further Notes:
- This behavior has been there from the 1st time I used IT with its previous versions prior to 0.25 on previous versions of FF as well.

**Comment by CAFxX** [comment]
Fixed on trunk.
