### ISSUE TITLE
v0.25 incompatible with Firefox 13.0.1

### ISSUE THREAD

**Issue by ghost** [CAFxX/ImageTweak#27]
Hello CAFxX
Yesterday Firefox updated my addons and ever since ImageTweak wasn't working anymore.
I saw that in your install.rdf it says "minVersion 13._" which should work cause 3._ includes 3.0.1 if you ask me.
But still Firefox didn't like that.
So I downloaded the sourcecode and set minVersion to 13.0.1 and finally Firefox like the addon again.

**Comment by CAFxX** [comment]
I'm pushing a new version to AMO with minVersion "13.0" instead of "13.*".
