### ISSUE TITLE
On firefox 38. addon creates ghost tabs.

### ISSUE THREAD

**Issue by ACIIL** [CAFxX/ImageTweak#39]
Close and opening tabs, not just photos, can leave blank tabs or tabs which cannot be seen in the tab bar when imageTweak is enabled. Error stops when disabled and restart resumed.
Sorry i cannot be more of help, users in the forum thread are posting details of the bug.

**Comment by RNiK** [comment]
Dupe of issue #37 .

**Comment by ACIIL** [comment]
new update fixed it. Thanks for the effort.
