### ISSUE TITLE
Version ..22 upgrade causes Address Bar to say:  "Search Bookmarks and History"

### ISSUE THREAD

**Issue by mkanet** [CAFxX/ImageTweak#6]
Ever since I upgraded to the new .22 version, instead of seeing the current website I'm on in the address bar (which I copy to clipboard regularly), is replaced with, "Search Bookmarks and History".  

If this is a "feature", I think it would be better to make that an option; not a default.  Ive used ImageTweak since the very beginning.  This is the first version that I've ever had an issue.  I was actually very surprised to see an issue.

If it's a feature, could you please mention how to return behavior back to normal?  If not, is there a pre-release version (or temporary patch) that fixes this?

Here is what I see instead of the webpage address:
http://i67.photobucket.com/albums/h283/mkanet/Screenshot-000008.jpg

**Comment by CAFxX** [comment]
Sorry, that has nothing to do with ImageTweak. If you won't take my word for it, follow the instructions on [this page](https://github.com/CAFxX/ImageTweak/wiki/Troubleshooting) to convince yourself.
