### ISSUE TITLE
Fullscreen Issues

### ISSUE THREAD

**Issue by TimTheEvoker** [CAFxX/ImageTweak#7]
After the upgrade to version .22, I cannot keep Firefox fullscreened.  No matter what I am viewing fullscreen, be it an image or a webpage, anytime I switch tabs or click a link, it will exit out of fullscreen.

As I generally use fullscreen to view images, this behaviour is quite annoying, and I'm beginning to wonder what I'd rather deal with: constantly needing to hit F11, or the default firefox image viewer.

I am currently using the latest version of FF4. I have been able to reproduce this bug on both of my linux boxes, as well as one of my windows boxes, so the bug seems to be OS independent.

**Comment by CAFxX** [comment]
Already fixed on trunk. Thank you for the detailed bug report.
If you don't wish to wait for 0.23 to come out, either install the trunk version or manually patch imagetweak.js in your profile folder with this commit: https://github.com/CAFxX/ImageTweak/commit/ad2338f47d43c9515f686b9f9b560f4b20f4e0d5
