### ISSUE TITLE
Firefox exits full screen mode when loading a new page

### ISSUE THREAD

**Issue by SidneyNettleson** [CAFxX/ImageTweak#8]
I tried this on Windows XP Professional and Windows 7 Professional with Firefox 4.0.1 and a clean profile, no other Extensions installed.

Behavior: When in full screen mode (F11) the following actions cause the browser to exit full screen mode:
- clicking a link (anchors that just jump to a different position on the same page excluded)
- submitting a form
- entering anything in the address bar and submitting with mouse or keyboard
- entering anything (or nothing) in the search field and submitting with mouse or keyboard
- refreshing the page with mouse (refresh button or context menu) or keyboard (F5, CTRL+R)
- possibly more?

[EDIT]I just realized this or something similar is already in the list of closed issues. I'll try the manual patch and report back.[/EDIT]

[EDIT]The patch mentioned here https://github.com/CAFxX/ImageTweak/issues/7 fixed the issue.[/EDIT]

**Comment by CAFxX** [comment]
Thank you anyway for the detailed bug report!
