### ISSUE TITLE
Can't drag Images

### ISSUE THREAD

**Issue by ghost** [CAFxX/ImageTweak#9]
I'm using EasyDragToGo to save images by dragging them. 

About two years ago I couldn't drag images once I installed ImageTweak. I asked you about that and you told me to press CTRL while dragging and that worked well back then.

At some point later you released a version of ImageTweak that made the dragging work without pressing CTRL.

But now I switched to Firefox 4 and I can't drag images anymore at all (neither with nor without pressing CTRL). I'm not sure if it's a problem with Firefox 4 or the new version of ImageTweak since 0.22 was just released when I switched.

Any tips? :/

**Comment by CAFxX** [comment]
I just fixed a similar problem with another dragging extension (https://github.com/CAFxX/ImageTweak/issues/5). If you can provide a solution similar to the one reported in that link I will try to fix it.

**Comment by CAFxX** [comment]
@mikkore, if you can provide me with what I asked in the previous message, I can try to fix it. Otherwise I will have to close this issue...

**Comment by ardaleth** [comment]
I am having this issue as well. In 0.21 dragging the image behaved as in any other page (showing the "ghost" image of the picture and triggering Easy DragtoGo), but after 0.21 this stopped working. Now if I try to click and drag the picture, I can only move it around the screen - whether Easy DragtoGo is installed or not. Pressing Ctrl or Command changes nothing. 

I am on OS X 10.7, Firefox 12.0.

**Comment by CAFxX** [comment]
Even if the ghost image is disabled (it would be a pain in the **\* if it showed up every time you're moving the image around!), you should be able to drag&drop the image to your desktop (or other folder) to save it.
Feel free to reopen if this is not the case.
